// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220710122106_SeedDataDarkstore")]
    partial class SeedDataDarkstore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationCore.Entities.Darkstore", b =>
                {
                    b.Property<int>("DarkstoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DarkstoreId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DarkstoreId");

                    b.ToTable("Darkstores");

                    b.HasData(
                        new
                        {
                            DarkstoreId = 1,
                            Name = "Brooklyn"
                        },
                        new
                        {
                            DarkstoreId = 2,
                            Name = "The Bronx"
                        },
                        new
                        {
                            DarkstoreId = 3,
                            Name = "Queens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
